import "./App.css";
import Navbar from "./components/Navbar";
import React, { Component } from "react";
import News from "./components/News";
import { BrowserRouter, Route, Routes } from "react-router-dom";
export default class App extends Component {
  render() {
    return (
      <div>
        <BrowserRouter>
          <Navbar />
          <Routes>
            <Route
              exact
              path="/"
              element={
                <News
                  key="general"
                  pageSize={8}
                  category={"general"}
                  country={"in"}
                />
              }
            />
            <Route
              exact
              path="/business"
              element={
                <News
                  key="business"
                  pageSize={8}
                  category={"business"}
                  country={"in"}
                />
              }
            />
            <Route
              exact
              path="/entertainment"
              element={
                <News
                  key="entertainment"
                  pageSize={8}
                  category={"entertainment"}
                  country={"in"}
                />
              }
            />
            <Route
              exact
              path="/health"
              element={
                <News
                  key="health"
                  pageSize={8}
                  category={"health"}
                  country={"in"}
                />
              }
            />
            <Route
              exact
              path="/science"
              element={
                <News
                  key="science"
                  pageSize={8}
                  category={"science"}
                  country={"in"}
                />
              }
            />
            <Route
              exact
              path="/sports"
              element={
                <News
                  key="sports"
                  pageSize={8}
                  category={"sports"}
                  country={"in"}
                />
              }
            />
            <Route
              exact
              path="/tech"
              element={
                <News
                  key="tech"
                  pageSize={8}
                  category={"technology"}
                  country={"in"}
                />
              }
            />
          </Routes>
        </BrowserRouter>
      </div>
    );
  }
}
